-- MySQL Script generated by MySQL Workbench
-- 11/17/15 19:05:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_inmo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_inmo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_inmo` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `db_inmo` ;

-- Only for update schema
-- ALTER SCHEMA `db_inmo`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_unicode_ci;
-- ----------------------------------------------------------------------------------

-- -----------------------------------------------------
-- Table `db_inmo`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inmo`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `deleted_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inmo`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inmo`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `apellido` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `telefono` INT NOT NULL COMMENT '',
  `rol_id` INT NOT NULL COMMENT '',
  `clave` VARCHAR(200) NOT NULL COMMENT '',
  `remember_token` VARCHAR(200) NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `deleted_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`, `rol_id`)  COMMENT '',
  INDEX `fk_User_Rol_idx` (`rol_id` ASC)  COMMENT '',
  CONSTRAINT `fk_User_Rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `db_inmo`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inmo`.`propietarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inmo`.`propietarios` (
  `id` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `apellido` VARCHAR(45) NOT NULL COMMENT '',
  `telefono` INT NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `clave` VARCHAR(200) NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `deleted_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inmo`.`conjuntos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inmo`.`conjuntos` (
  `id` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `direccion` VARCHAR(45) NOT NULL COMMENT '',
  `ciudad` VARCHAR(45) NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `deleted_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inmo`.`tipo_propiedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inmo`.`tipo_propiedades` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `deleted_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inmo`.`propiedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inmo`.`propiedades` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `numero_pisos` INT NOT NULL COMMENT '',
  `tipo_propiedad_id` INT NOT NULL COMMENT '',
  `conjunto_id` INT NOT NULL COMMENT '',
  `propietario_id` INT NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `deleted_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `Propietario-id_idx` (`propietario_id` ASC)  COMMENT '',
  INDEX `Conjunto-id_idx` (`conjunto_id` ASC)  COMMENT '',
  INDEX `Tipo-id_idx` (`tipo_propiedad_id` ASC)  COMMENT '',
  CONSTRAINT `Propietario-id`
    FOREIGN KEY (`propietario_id`)
    REFERENCES `db_inmo`.`propietarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Conjunto-id`
    FOREIGN KEY (`conjunto_id`)
    REFERENCES `db_inmo`.`conjuntos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tipo-id`
    FOREIGN KEY (`tipo_propiedad_id`)
    REFERENCES `db_inmo`.`tipo_propiedades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inmo`.`tipo_deudas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inmo`.`tipo_deudas` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `concepto` VARCHAR(45) NOT NULL COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `deleted_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inmo`.`deudas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inmo`.`deudas` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  `valor` DOUBLE NOT NULL COMMENT '',
  `conjunto_id` INT NOT NULL COMMENT '',
  `tipo_deuda_id` INT NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `deleted_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Deudas_Conjunto1_idx` (`conjunto_id` ASC)  COMMENT '',
  INDEX `tipoDeuda_id_idx` (`tipo_deuda_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Deudas_Conjunto1`
    FOREIGN KEY (`conjunto_id`)
    REFERENCES `db_inmo`.`conjuntos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipoDeuda_id`
    FOREIGN KEY (`tipo_deuda_id`)
    REFERENCES `db_inmo`.`tipo_deudas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inmo`.`forma_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inmo`.`forma_pago` (
  `id` INT NOT NULL COMMENT '',
  `efectivo` TINYINT(1) NULL COMMENT '',
  `consignacion` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inmo`.`tipo_pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inmo`.`tipo_pagos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `concepto` VARCHAR(45) NOT NULL COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `deleted_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inmo`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_inmo`.`pagos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo_pago_id` INT NOT NULL COMMENT '',
  `valor` DOUBLE NOT NULL COMMENT '',
  `descripcion` VARCHAR(200) NOT NULL COMMENT '',
  `fecha_inicial` DATE NOT NULL COMMENT '',
  `fecha_final` DATE NOT NULL COMMENT '',
  `propiedad_id` INT NOT NULL COMMENT '',
  `fecha_pago` VARCHAR(45) NULL COMMENT '',
  `forma_pago_id` INT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `deleted_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `tipoPago-id_idx` (`tipo_pago_id` ASC)  COMMENT '',
  INDEX `fk_pagos_propiedades1_idx` (`propiedad_id` ASC)  COMMENT '',
  INDEX `fk_pagos_forma_pago1_idx` (`forma_pago_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pagos_forma_pago1`
    FOREIGN KEY (`forma_pago_id`)
    REFERENCES `db_inmo`.`forma_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_propiedades1`
    FOREIGN KEY (`propiedad_id`)
    REFERENCES `db_inmo`.`propiedades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipoPago-id`
    FOREIGN KEY (`tipo_pago_id`)
    REFERENCES `db_inmo`.`tipo_pagos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
